version: "3.8"

services:
  backend-flask:
    environment:
      FRONTEND_URL: "*"
      BACKEND_URL: "*"
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      OTEL_SERVICE_NAME: backend-flask
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
      AWS_DEFAULT_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    networks:
      - internal-network
    

  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "*"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
    networks:
      - internal-network

  # xray-daemon:
  #   image: amazon/aws-xray-daemon
  #   container_name: xray-daemon
  #   environment:
  #     AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  #     AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  #     AWS_REGION: "us-east-1"
  #   command: ["xray-daemon", "-o"]
  #   ports:
  #     - "2000:2000/udp"
  #   networks:
  #     - internal-network

  # db:
  #   image: postgres:13-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db:/var/lib/postgresql/data
  #   networks:
  #     - internal-network

  # dynamodb-local:
  #   # Needed to avoid permission issues with local volume
  #   user: root
  #   image: amazon/dynamodb-local:latest
  #   container_name: dynamodb-local
  #   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - "./docker/dynamodb:/home/dynamodblocal/data"
  #   working_dir: /home/dynamodblocal
  #   networks:
  #     - internal-network

  # dynamodb-admin:
  #   image: aaronshaf/dynamodb-admin
  #   container_name: dynamodb-admin
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     DYNAMO_ENDPOINT: http://dynamodb-local:8000
  #   depends_on:
  #     - dynamodb-local
  #   networks:
  #     - internal-network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   depends_on:
  #     - db
  #   networks:
  #     - internal-network


# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks:
  internal-network:
    driver: bridge
    name: cruddur

volumes:
  db:
    driver: local
